# Generated by Django 5.0.1 on 2024-02-09 17:21

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=30, verbose_name='ФИО')),
                ('nickname', models.CharField(default='-', max_length=20, verbose_name='Укажите свой ник')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('instagram', models.CharField(blank=True, max_length=30, verbose_name='Инстаграм')),
                ('telegram', models.CharField(blank=True, max_length=30, verbose_name='Тикток')),
                ('gender', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('Неопределенный', 'Неопределенный')], default='Неопределенный', max_length=20)),
                ('location', models.CharField(max_length=100, verbose_name='Место жительства')),
                ('language_skills', models.TextField(default='中文', verbose_name='Языки, которыми владеет пользователь')),
                ('experience', models.CharField(choices=[('Без опыта', 'Без опыта'), ('Менее года', 'Менее года'), ('Более года', 'Более года'), ('Больше 3 лет', 'Больше 3 лет')], max_length=40, verbose_name='Опыт работы')),
                ('bio', models.TextField(max_length=250, verbose_name='Чуть о себе')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
