# Generated by Django 5.0.1 on 2024-02-09 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmodel',
            options={},
        ),
        migrations.AlterModelManagers(
            name='accountmodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
