# Generated by Django 5.0.1 on 2024-02-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('location', models.TextField(max_length=300)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
