# Generated by Django 5.0.1 on 2024-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Хэштеги категорий')),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название одежды')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='Описание')),
                ('tags', models.ManyToManyField(to='clothes_app.tag', verbose_name='Категория')),
            ],
        ),
    ]
