# Generated by Django 5.0.1 on 2024-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='#', max_length=50, verbose_name='Хэштеги категорий'),
        ),
    ]
