# Generated by Django 5.0.1 on 2024-02-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('description', models.TextField(max_length=300, verbose_name='Опасние')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('actor', models.CharField(max_length=100, verbose_name='Актеры')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('trailer_url', models.URLField(verbose_name='Ссылка на трейлер')),
                ('genre', models.CharField(choices=[('Боевик', 'Боевик'), ('Комедия', 'Комедия'), ('Романтика', 'Романтика'), ('Триллеры', 'Триллеры')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300, verbose_name='Впечатления')),
                ('stars', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=40, verbose_name='Оценка фильма')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tv_show.movie')),
            ],
        ),
    ]
