# Generated by Django 5.0.1 on 2024-01-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('description', models.TextField(max_length=300, verbose_name='Опасние')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('actor', models.CharField(max_length=100, verbose_name='Актеры')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('trailer_url', models.URLField(verbose_name='Ссылка на трейлер')),
                ('genre', models.CharField(choices=[('Боевик', 'Боевик'), ('Комедия', 'Комедия'), ('Романтика', 'Романтика'), ('Триллеры', 'Триллеры')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
